import type { Metadata } from "next";
import { Header } from "@/components/shared/header/header";

export const metadata: Metadata = {
  title: "Pizza store",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen">
      <Header />
      {children}
      {modal}
    </main>
  );
}
